nguage: ruby
rvm:
- 2.3.0
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
  api_key:
    secure: f95lzH99Y/T4VytFTvqe/1WnybKUrsKqbn8OCpYec4bmxFDHGTKP73VnnNzKciqul1dhWHDDx/oeifYFtAzZjS0b0Lz6hYmn5/3liDB+oo+MhcNeElXv4IaZZ7yk3KQZ6EqI8nsJoS/rvZIiR7ayHQZCDYjW7wTM/a5wFCN0YXjxn0i18xBPEnZbdL5Sdvtr5sFIiASpDlQE6OstYpu6NZ1NOU32tZ9CqEMBlTFMhXJH0t5ZZtAk0caOPC/JzVpa1M/XHKJ4ypjEAsRoUlPmXiKPs/Sfh7PFsnkoyRMO3TCKnbj4CHu+FcMzJ6w1Op0C9PhbG17hSVksaEG5Xio37uVQ0P7afWGRwaddIOMDs4itHEulSonLUEY/r701hypXcsOZjlm1aP3x/o6JSl7CcwRPlg20na8f8BSOU874S/CerEN8+2php/4iA5JOjUUDgeovA5Yflsml0V2k2NHC5WywdpCaeaCLZPUHDlaPWyANO2aItvVrlJDMlgLGy2AMD3uMwKpL5oD+0rYaRG00iG3jf5vDkdBt/tvvk2lszqb83AVO+jo84gVUBlRAyRgh1pS3J4fuuH5pltjtAtV/Sbjye0MlzRIuPZeOgXfdFa5JymHhCKBpxWK9hfFdeVsWNifnfEn1B+9Lb0VwK1/K/dv3FXR4KPawS58cUmCgZ8M=
  run: rake db:migrate
  app: enigmatic-tundra-35451
  on:
    repo: Mayse/ratebeer
APIKEY=28be4cd4e2d7e02dc06571c297b470bf:
  secure: pFkEslM30al1CoNcdL8o9Ip9rlAZ+fxEwSlQGt7RJLliekg8/B0cGabopsUX8JPTYvsrBmLg5ptUpIP0JXomQeW9uqn4KjUQ2KBPCyb0m6gPls/BgAHKq3jRFfISZvugtllWcXxr0cngE+9okFbClDRmv15Eo1X9b7tZoUSK+j/IICRDsd9nNKOsaZy2yjUBC+XKc5+JlIKcrKqaEvR+vx2r3OXXnWfl8RqUV5LKsMxpxguD//ZdFoUaCRoBsjNpzKQb2MiKBAKyw9jX+pslT6eK9vy2B2dmI/G9WnInwQhJxH8ez1OEcl8HboGUrcq9PAJG3keUdeH76UtsXL9vjMVzU9jA6zZWW8sL468yI3GcXB4RkmDTWfleLIFyP/0Qxod+Ib2+lB21o0tO/IrtuNFSZfwot25+ovl8hQxzCg1sqqi5z8ItTtc8o8i7RaGBBgpWMdFgMcSK14PBHNG9x6QdEHt2h2z4HL9B4429/gV1p6bHu2mGQCauBN5hKRPoCU4yi+i44vZe+B1Cqc4UOpPIV+TRnCXlUuK/HMnAfa8ZxZOucoslMzK9VE2nE3fbOsT2aX0fmxHDgRlxZgrjB3ueKHAKLpcP8+XxNjUs23eKyZcsWUS7zwLNwPyFoDuLo9Z9kaj9GSxaPx9LUzSOGIdLQRJdC4eNpni4iffM2lk=
